pipeline {
    agent any
    
    triggers {
        // Run every Monday at 9:00 AM
        cron('0 9 * * 1')
    }
    
    environment {
        // Jira credentials stored in Jenkins Credentials
        JIRA_URL = credentials('jira-url')
        JIRA_EMAIL = credentials('jira-email')
        JIRA_API_TOKEN = credentials('jira-api-token')
        
        // PostgreSQL connection (if needed for release readiness)
        // POSTGRES_HOST = credentials('postgres-host')
        // POSTGRES_DB = credentials('postgres-db')
        // POSTGRES_USER = credentials('postgres-user')
        // POSTGRES_PASSWORD = credentials('postgres-password')
        
        // Release version to track
        VERSION = '10.13.0.0'
    }
    
    stages {
        stage('Checkout') {
            steps {
                // Clone the repository
                git branch: 'main',
                    url: 'https://github.com/rdwr-eranp/defensepro-jira-monitor.git'
            }
        }
        
        stage('Setup Python Environment') {
            steps {
                script {
                    if (isUnix()) {
                        sh '''
                            python3 -m pip install --upgrade pip
                            pip install -r requirements.txt
                        '''
                    } else {
                        bat '''
                            python -m pip install --upgrade pip
                            pip install -r requirements.txt
                        '''
                    }
                }
            }
        }
        
        stage('Generate Weekly Report') {
            steps {
                script {
                    def timestamp = new Date().format('yyyy-MM-dd_HHmm')
                    echo "Generating weekly report for version ${VERSION}"
                    
                    if (isUnix()) {
                        sh "python3 weekly_work_summary.py"
                    } else {
                        bat "python weekly_work_summary.py"
                    }
                }
            }
        }
        
        stage('Archive Reports') {
            steps {
                // Archive HTML and CSV reports as Jenkins artifacts
                archiveArtifacts artifacts: '**/*.html, **/*.csv', 
                                 allowEmptyArchive: false,
                                 fingerprint: true,
                                 onlyIfSuccessful: true
            }
        }
        
        stage('Publish Reports') {
            steps {
                // Publish HTML reports for viewing in Jenkins
                publishHTML([
                    allowMissing: false,
                    alwaysLinkToLastBuild: true,
                    keepAll: true,
                    reportDir: '.',
                    reportFiles: 'weekly_work_summary_*.html',
                    reportName: 'Weekly Work Summary',
                    reportTitles: 'DefensePro Weekly Report'
                ])
                
                publishHTML([
                    allowMissing: false,
                    alwaysLinkToLastBuild: true,
                    keepAll: true,
                    reportDir: '.',
                    reportFiles: 'open_bugs_report.html',
                    reportName: 'Open Bugs Report',
                    reportTitles: 'Open Bugs Across Releases'
                ])
            }
        }
        
        stage('Email Notification') {
            steps {
                script {
                    def reportDate = new Date().format('MMMM dd, yyyy')
                    
                    emailext(
                        subject: "DefensePro ${VERSION} - Weekly Report (${reportDate})",
                        body: """
                        <h2>DefensePro Weekly Status Report</h2>
                        <p><strong>Release Version:</strong> ${VERSION}</p>
                        <p><strong>Report Date:</strong> ${reportDate}</p>
                        <p><strong>Build:</strong> #${BUILD_NUMBER}</p>
                        
                        <h3>Reports Generated:</h3>
                        <ul>
                            <li><a href="${BUILD_URL}Weekly_20Work_20Summary/">Weekly Work Summary</a></li>
                            <li><a href="${BUILD_URL}Open_20Bugs_20Report/">Open Bugs Report</a></li>
                            <li><a href="${BUILD_URL}artifact/">Download Artifacts (HTML/CSV)</a></li>
                        </ul>
                        
                        <p>View full details in Jenkins: <a href="${BUILD_URL}">${BUILD_URL}</a></p>
                        
                        <hr>
                        <p><em>Automated report generated by Jenkins</em></p>
                        """,
                        mimeType: 'text/html',
                        to: 'eranp@radware.com',
                        attachmentsPattern: '**/weekly_work_summary_*.html, **/open_bugs_report.html',
                        attachLog: false
                    )
                }
            }
        }
    }
    
    post {
        success {
            echo '✓ Weekly report generated successfully!'
        }
        failure {
            emailext(
                subject: "FAILED: DefensePro Weekly Report - ${env.VERSION}",
                body: """
                <h2>Weekly Report Generation Failed</h2>
                <p><strong>Build:</strong> #${BUILD_NUMBER}</p>
                <p><strong>Status:</strong> FAILED</p>
                
                <p>Check the console output: <a href="${BUILD_URL}console">${BUILD_URL}console</a></p>
                """,
                mimeType: 'text/html',
                to: 'eranp@radware.com'
            )
        }
        always {
            // Clean up workspace if needed
            cleanWs(
                deleteDirs: true,
                notFailBuild: true,
                patterns: [[pattern: '*.pyc', type: 'INCLUDE']]
            )
        }
    }
}
